// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYAPaeJUsMyNGcEm12wUFQCC0uZvtwRXE',
    appId: '1:398326233194:web:54bdbf1c5c7435874fb213',
    messagingSenderId: '398326233194',
    projectId: 'thegarments-365d0',
    authDomain: 'thegarments-365d0.firebaseapp.com',
    storageBucket: 'thegarments-365d0.firebasestorage.app',
    measurementId: 'G-0KHGB4SKTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_rXtmgabad6VI4gkxCIXDbR-1yHhmopw',
    appId: '1:398326233194:android:e2f319daf685707d4fb213',
    messagingSenderId: '398326233194',
    projectId: 'thegarments-365d0',
    storageBucket: 'thegarments-365d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp1xcK7nH8-Cx4-jsqUqzwncgVr1qBrxQ',
    appId: '1:398326233194:ios:bfb4c36b4826330f4fb213',
    messagingSenderId: '398326233194',
    projectId: 'thegarments-365d0',
    storageBucket: 'thegarments-365d0.firebasestorage.app',
    iosBundleId: 'com.example.thegarments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp1xcK7nH8-Cx4-jsqUqzwncgVr1qBrxQ',
    appId: '1:398326233194:ios:bfb4c36b4826330f4fb213',
    messagingSenderId: '398326233194',
    projectId: 'thegarments-365d0',
    storageBucket: 'thegarments-365d0.firebasestorage.app',
    iosBundleId: 'com.example.thegarments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYAPaeJUsMyNGcEm12wUFQCC0uZvtwRXE',
    appId: '1:398326233194:web:d9b7182241b7fc5b4fb213',
    messagingSenderId: '398326233194',
    projectId: 'thegarments-365d0',
    authDomain: 'thegarments-365d0.firebaseapp.com',
    storageBucket: 'thegarments-365d0.firebasestorage.app',
    measurementId: 'G-P1KK98YFV3',
  );
}
